Rate : Calificacion 
Name : Nombre
Descripcion : Descripcion
NewDocument : Nuevo Documento 
Submit : Cargar
One : uno
Two : dos 
Three : tres
Four : Cuatro
Five : Cinco
MyDocuments: Mis Documentos 
Logout : Salir
Login : Ingresar
DocumentList : Lista de documentos
Filerq : Archivo Requerido
FileContent : ¿Que hay en el archivo?
Shared : Compartir
SharedFiles : Documentos Compartidos 
Download : Descargar
Del : Borrar
EditDocument : Editar Documento
EditDoc : Editar